### ISSUE TITLE
falco exits with a segfault within minutes of starting service

### ISSUE THREAD

**Issue by kartikeyap** [draios/falco#215] opened 2017-03-02 11:44 UTC
I am just starting out with Falco in a test setup. Unfortunately I am running into recurring segfaults within minutes of starting the service. I am running Ubuntu Trusty, with kernel 3.13.0. eg:

Mar  2 10:38:27 host1000 falco: Falco initialized with configuration file /etc/falco.yaml
Mar  2 10:38:27 host1000 falco: Parsed rules from file /etc/falco_rules.yaml
`<snip>`
`<snip>`
Mar  2 10:39:03 host1000 falco: 10:39:03.452799016: Warning Shell spawned by untrusted binary (user=nobody shell=sh parent=scribe_spool_co cmdline=sh -c find /var/spool/databus/ -type f -exec du -c {} + 2>/dev/null | awk '$2 == "total" { print $1 }')
Mar  2 10:39:04 host1000 falco: 10:39:04.640856478: Warning File below /etc opened for writing (user=root command=supervise service-collectd-fix file=/etc/service-collectd-fix/supervise/status.new)
Mar  2 10:39:04 host1000 falco: 10:39:04.641404283: Warning File below /etc opened for writing (user=root command=supervise service-collectd-fix file=/etc/service-collectd-fix/supervise/status.new)
Mar  2 10:39:05 host1000 kernel: [25579336.102168] falco[12183]: segfault at 7f8d6e645000 ip 00000000004b1b14 sp 00007fffeabc9f00 error 4 in falco[400000+602000]

**Comment by mstemm** [comment] 2017-03-02 17:16
Thanks for the report. Can you tell us what version of falco you're using, what rules file you're using (default one that comes w falco vs customized), and what falco config file you're using? Also if you're running falco on the command line the command line you're using would be helpful also.

**Comment by kartikeyap** [comment] 2017-03-03 04:42
Hey @mstemm ,
Thank you for looking into it. Here is the required information.
Version: 0.5.0
Rules and config: Default
Command line: sudo falco -c /etc/falco.yaml -r /etc/falco_rules.yaml -v

I have tried running Falco with `sudo service falco start` as well, but with same results.

**Comment by mstemm** [comment] 2017-03-07 16:48
I've been able to reproduce a crash with 0.5.0. I'm still investigating to find the root cause and will update this issue when I know more.

**Comment by mstemm** [comment] 2017-03-07 17:48
I think the source of the problem is an incompatibility between the sysdig-probe driver that comes with sysdig 0.15.0 and falco. Falco re-uses the kernel driver from sysdig rather than have its own kernel driver.

To see if this is the cause of your crashes, can you do the following:

 - apt-get remove falco
 - apt-get remove sysdig
 - sudo rmmod sysdig-probe
 - apt-get install sysdig=0.14.0
 - apt-get install falco

Then try running falco again and let me know if you see crashes.

**Comment by kartikeyap** [comment] 2017-03-08 08:21
Thanks @mstemm. Changing the sysdig-probe driver seems to have fixed the issue. Falco has not crashed in over an hour. I will keep the process under observation for next few hours and reopen the issue if need arise.

**Comment by mstemm** [comment] 2017-03-20 20:56
I'm going to re-open this to track updating falco to have its own standalone kernel driver. This way you won't have compatibility problems between sysdig's driver and what falco is expecting.

**Comment by mstemm** [comment] 2017-03-25 04:37
Fixed in #224.

**Closed by mstemm** 2017-03-25 04:37 UTC
